# Generated by Django 3.0.5 on 2021-05-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productaname', models.CharField(default='NA', max_length=255)),
                ('producttype', models.CharField(choices=[('Chair', 'Chair'), ('Table', 'Table'), ('others', 'others')], max_length=255)),
                ('productqty', models.IntegerField()),
                ('productprice', models.IntegerField(default='NA')),
                ('productdesc', models.TextField()),
            ],
        ),
    ]
