# Generated by Django 3.0.5 on 2021-05-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producttopping',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
