# Generated by Django 3.0.5 on 2021-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_producttopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_logo_url',
            field=models.ImageField(default='ProductImages/product.png', upload_to='ProductImages/'),
        ),
    ]
